name: Build wheels

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build_wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install cibuildwheel
        run: pip install cibuildwheel==2.20.0

      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: "pp* *musllinux*"
          # soporta Apple Silicon y x86_64
          CIBW_ARCHS_MACOS: "x86_64 arm64 universal2"
          # soporta 64 bits en Linux y Windows
          CIBW_ARCHS_LINUX: "x86_64 aarch64"
          CIBW_ARCHS_WINDOWS: "AMD64"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*

  # Opcional: Publicar automáticamente en PyPI al hacer tag v*
  upload_pypi:
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels-ubuntu-latest
          path: dist
      - uses: actions/download-artifact@v4
        with:
          name: wheels-windows-latest
          path: dist
      - uses: actions/download-artifact@v4
        with:
          name: wheels-macos-latest
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

